[package]
name = "libfat"
version = "0.1.0"
authors = ["Thog <me@thog.eu>"]
edition = "2018"

[dependencies]
byteorder = "1.0"
log = "0.4.6"
structview = { version = "0.3", default-features = false }
libfs = { path = "../libfs" }
storage_device = { path = "../storage_device" }

[dependencies.arrayvec]
default-features = false
version = "0.4.10"
features = ["array-sizes-33-128"]

[dependencies.num-traits]
version = "0.2"
default-features = false
